name: Trigger Location Update

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Multiple triggers
        run: |
          for i in {1..5}; do
            echo "Trigger $i of 5"
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/dispatches \
              -d '{"event_type":"update_location"}'
            if [ $i -lt 5 ]; then
              sleep 60
            fi
          done
