name: Fetch Garmin Location

on:
  repository_dispatch:
    types: [update_location]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-kml:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run fetch-latest-point script
        env:
          GARMIN_USER: ${{ secrets.GARMIN_USER }}
          GARMIN_PASS: ${{ secrets.GARMIN_PASS }}
        run: node fetch-latest-point.js

      - name: Update GPX files list
        run: node update-gpx-files.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update history tracking points [skip ci]"
          git pull --rebase
          git push
